apiVersion: v1
kind: Namespace
metadata:
  name: admission
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission
  namespace: admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission
subjects:
  - kind: ServiceAccount
    name: admission
    namespace: admission
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: admission-controller
  namespace: admission
spec:
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      restartPolicy: Always
      serviceAccountName: admission
      containers:
        - name: push-secret
          # image name will be patched during installation
          # TODO: can we use FQDN?
          image: todo/tool
          imagePullPolicy: Always
  replicas: 1