apiVersion: v1
kind: Namespace
metadata:
  name: admission
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission
  namespace: admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission
subjects:
  - kind: ServiceAccount
    name: admission
    namespace: admission
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: admission-controller
  namespace: admission
spec:
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      restartPolicy: Always
      serviceAccountName: admission
      containers:
        - name: main
          env:
            - name: ROCKET_LOG_LEVEL
              value: normal
            - name: ROCKET_ADDRESS
              value: '0.0.0.0'
            - name: ROCKET_TLS
              value: '{certs="/tls/crt",key="/tls/key"}'
          # image name will be patched during installation
          image: todo/tool
          imagePullPolicy: Always
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-svc
  namespace: admission
spec:
  selector:
    app: admission-controller
  ports:
  - port: 443
    targetPort: 8000
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-controller.d-k8s.io
webhooks:
  - name: admission-controller.d-k8s.io
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        namespace: admission
        name: admission-controller-svc
        path: /admission
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: IfNeeded
    failurePolicy: Ignore