apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: main
---
apiVersion: v1
kind: Service
metadata:
  name: app-ss
spec:
  clusterIP: None
  selector:
    app: app
  ports:
    - port: 80
      targetPort: main
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  serviceName: app-ss
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: cr.local/example-shared-storage
          ports:
            - containerPort: 8080
              name: main
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteMany
        selector:
          matchLabels:
            volume-id: shared-storage-example-data
        storageClassName: local-volume
        resources:
          requests:
            storage: 1Gi
