apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration

apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
    - "__PUB_IP__"
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kubernetesVersion: v1.19.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
