apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configure-dockerd
  namespace: registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-dockerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: configure-dockerd
    namespace: registry
---
kind: Job
apiVersion: batch/v1
metadata:
  name: configure-dockerd
  namespace: registry
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      serviceAccount: configure-dockerd
      initContainers:
        - name: login
          image: docker
          envFrom:
            - secretRef:
                name: registry-credentials
              prefix: CREDS_
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /root/.docker
              name: docker-config
          args:
            - login
            - $(CREDS_ADDRESS)
            - --username
            - $(CREDS_USERNAME)
            - --password
            - $(CREDS_PASSWORD)
      containers:
        - name: push-secret
          image: bitnami/kubectl
          volumeMounts:
            - mountPath: /.docker
              name: docker-config
          securityContext:
            runAsUser: 0
          args:
            - create
            - secret
            - generic
            - local
            - --from-file=.dockerconfigjson=/.docker/config.json
            - --type=kubernetes.io/dockerconfigjson
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-config
          emptyDir: {}
