apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
# This deployment will crash
# until k8s addons fixes it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: images
        hostPath:
          path: /var/docker-registry
          type: DirectoryOrCreate
      - name: certs
        secret:
          secretName: registry-certs
      - name: auth
        secret:
          secretName: registry-credentials
      - name: auth-rw
        emptyDir: {}
      initContainers:
      - name: auth-to-rw
        image: debian:stable-slim
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: auth
          mountPath: /from
        - name: auth-rw
          mountPath: /to
        args:
        - bash
        - -c
        - 'cp /from/* /to/'
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: 'Registry Realm'
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/credentials
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /pki/crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /pki/key
        ports:
        - containerPort: 443
        volumeMounts:
        - name: images
          mountPath: /var/lib/registry
        - name: auth-rw
          mountPath: /auth
        - name: certs
          mountPath: /pki
---
apiVersion: v1
kind: Service
metadata:
  labels:
     app: registry
  name: registry
  namespace: registry
spec:
  ports:
  - port: 443
    targetPort: 443
  type: NodePort
  selector:
    app: registry
