apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configure-dockerd
  namespace: registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-dockerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: configure-dockerd
    namespace: registry
